### ISSUE TITLE
Create an IFramed HTML output element

### ISSUE THREAD

**Issue by rgbkrk** [nteract/react-jupyter-display-area#6]
This is a component that can be swapped out in the default transforms that encapsulates unsafe outputs. Alternatively, the display area itself could be iframed.

/cc @kenwheeler @jdfreder

**Comment by jdfreder** [comment]
I did something like this for ipywidgets at one point in time.  I had to use messages to tell the parent to resize the iframe when the dom changed- sounds crazy but wasn't that bad in practice especially because ipywidgets has events I could listen to in order to know when I should try to resize.  With generic HTML we may need to use MutationObserver to know when to resize the iframe (for dynamic content).

**Comment by rgbkrk** [comment]
Yeah. One other thing this buys us if we did it by default is that we can reason about the document and application state without having someone change it out from under us.

**Comment by jdfreder** [comment]
Yeah, I'm 100% on board with this idea.

**Comment by rgbkrk** [comment]
Closing since this is managed on nteract/nteract for the monorepo.
